apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno-localreg-ca
  namespace: kyverno
data:
  localreg.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDIzCCAgugAwIBAgIUUwlK98UKiMteVVqUKbVm5B8gAmcwDQYJKoZIhvcNAQEL
    BQAwEzERMA8GA1UEAwwIbG9jYWxyZWcwHhcNMjYwNzEwMDc1NTUyWhcNMzYwNzA3
    MDc1NTUyWjATMREwDwYDVQQDDAhsb2NhbHJlZzCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBALOc8xURzz488TP0BjNjgUeIpWXjoIEP9GhChJab7TcUcCoQ
    Ae+9qZZOQhr+G6Ghy69TiLwzb4WrMG8Zh2TAS0JhV4p6J9NCUv2IbvMsVUdjKgp7
    e3lQC/nGkutmFxIMGJznW5XTKfotSu9rknPl3QTRR/sXQKILXV0gDFuiJOQRipjT
    N6pyJTpGCApIv5NRxSLw56vaRp9NIp1IYuLxjtwdFVmaZNkxgy88Dqa6iHy/tIAu
    qAWhBRuDTmotnEtszzpbo/iPMqp9bcXdc7UAJCS8kSOdrhP6NpLpK3WFL4sEJaqr
    1baCBYerqKuxzbreyaX/BMgu2bEhIhHPCILvKVECAwEAAaNvMG0wHQYDVR0OBBYE
    FEC+ahE4aJkSu2BYed5e9L+76E1SMB8GA1UdIwQYMBaAFEC+ahE4aJkSu2BYed5e
    9L+76E1SMA8GA1UdEwEB/wQFMAMBAf8wGgYDVR0RBBMwEYcEwKgBPYIJbG9jYWxo
    b3N0MA0GCSqGSIb3DQEBCwUAA4IBAQCJPTaQuYtux+Qzjn4540GE+ee8harfDkzz
    dm+7pjXtJWK5lK/SU7UASfLYd7huarZZYFx3tymBmmuoNhVQrfUlmhypXNW9B1Ip
    z9Gj2pd6eHGQt2/3DzzNottAwaGk1kNUqroKtrWbX06mBeicBkk81T4f2QX6JPng
    ke31UrLNgr8h8aJ6s5Wudt2e4Z2Qk3bVEkHzFDo+ISBCKMcH8vhvvh/yPAoA5Bvm
    qyTwaJxjLM0Ok/DVnKM766riFwq4e7Na3x5XJ1F9W8O0G40QrtEHVWuUeoaZHZGl
    kJWz0bGEZ4JqHaAOR6Q1PDyfdjJYKoz9Zy+bDxJYVnmcZOMHtpNz
    -----END CERTIFICATE-----
